### PR TITLE
update ck2yaml to latest version

### PR DESCRIPTION
**Pull request by 12Chao**

### CODE REVIEW

**Comment by bryanwweber** [comment]
Looks good to me! :+1:

**Comment by rwest** [comment]
Looks good to me too. Because your second commit just removes a file you added by mistake in your first commit, this is  good example of a time to "rebase" the branch (and combine those two commits) before merging the branch and closing the pull request. Good for you to practice some more git!  

Do an interactive rebase, and mark the second commit as a "fixup".

Also, if you "edit" the first commit, you could un-stage the  ChemCheck/db.sqlite3 - because I see no reason (from the commit message) which that file should have to be changed.

**Comment by 12Chao** [comment]
Thanks for the instruction, I just combined the commits and unstaged db.sqlite3.

**Comment by rwest** [comment]
Great.
But....  Ray just made a few more small changes to the script.  It has now been merged to the official master branch so is unlikely to change again soon. 
https://github.com/Cantera/cantera/blob/master/interfaces/cython/cantera/ck2yaml.py

**Pull request closed without merging**
